language: ruby
cache: bundler
rvm:
  - 2.2.2
script:
  - bundle exec rspec
before_script:
  - psql -c 'create database barriga_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
