default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: barriga_development

test:
  <<: *default
  database: barriga_test

production:
  <<: *default
  database: barriga_production
